//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_QuanLyThuChi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongViec
    {
        public int MaCV { get; set; }
        public System.DateTime Ngay { get; set; }
        public string Gio { get; set; }
        public string NoiDung { get; set; }
        public string ThanhVien { get; set; }
        public Nullable<int> ThongBao { get; set; }
        public Nullable<int> HoanThanh { get; set; }
        public Nullable<int> DaThongBao { get; set; }
        public string ThuChi { get; set; }
        public Nullable<double> SoTien { get; set; }
    
        public virtual ThanhVien ThanhVien1 { get; set; }
    }
}
