//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_QuanLyThuChi
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoanChi
    {
        public string MaKC { get; set; }
        public string MaThanhVien { get; set; }
        public System.DateTime Ngay { get; set; }
        public string LoaiKC { get; set; }
        public string KhoanChi1 { get; set; }
        public double SoTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual LoaiKhoanChi LoaiKhoanChi { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
