//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiKhoanThu
    {
        public LoaiKhoanThu()
        {
            this.KhoanThus = new HashSet<KhoanThu>();
        }
    
        public string MaLKT { get; set; }
        public string TenLKT { get; set; }
    
        public virtual ICollection<KhoanThu> KhoanThus { get; set; }
    }
}
