//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiKhoanChi
    {
        public LoaiKhoanChi()
        {
            this.KhoanChis = new HashSet<KhoanChi>();
        }
    
        public string MaLKC { get; set; }
        public string TenLKC { get; set; }
    
        public virtual ICollection<KhoanChi> KhoanChis { get; set; }
    }
}
