//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class QLThuChiEntities1 : DbContext
    {
        public QLThuChiEntities1()
            : base("name=QLThuChiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CongViec> CongViecs { get; set; }
        public DbSet<KhoanChi> KhoanChis { get; set; }
        public DbSet<KhoanThu> KhoanThus { get; set; }
        public DbSet<LanDangNhap> LanDangNhaps { get; set; }
        public DbSet<LoaiCamXuc> LoaiCamXucs { get; set; }
        public DbSet<LoaiKhoanChi> LoaiKhoanChis { get; set; }
        public DbSet<LoaiKhoanThu> LoaiKhoanThus { get; set; }
        public DbSet<LoaiVay> LoaiVays { get; set; }
        public DbSet<MucDichTietKiem> MucDichTietKiems { get; set; }
        public DbSet<NguoiVay> NguoiVays { get; set; }
        public DbSet<Quyen> Quyens { get; set; }
        public DbSet<ThanhVien> ThanhViens { get; set; }
        public DbSet<TietKiem> TietKiems { get; set; }
        public DbSet<TrangThai> TrangThais { get; set; }
        public DbSet<TraNo> TraNoes { get; set; }
        public DbSet<Vay_ChoVay> Vay_ChoVay { get; set; }
    
        public virtual ObjectResult<KhoanChoVayChuaTra_Result> KhoanChoVayChuaTra(string matv)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhoanChoVayChuaTra_Result>("KhoanChoVayChuaTra", matvParameter);
        }
    
        public virtual ObjectResult<KhoanVayChuaTra_Result> KhoanVayChuaTra(string matv)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhoanVayChuaTra_Result>("KhoanVayChuaTra", matvParameter);
        }
    
        public virtual int SP_CapNhatThongTinThanhVien(string tendangnhap, string matkhau, string cauhoi, string cautraloi, string tentv, Nullable<System.DateTime> ngaysinh, string gioitinh, string diavi, byte[] anh, string dienthoai, string email)
        {
            var tendangnhapParameter = tendangnhap != null ?
                new ObjectParameter("tendangnhap", tendangnhap) :
                new ObjectParameter("tendangnhap", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var cauhoiParameter = cauhoi != null ?
                new ObjectParameter("cauhoi", cauhoi) :
                new ObjectParameter("cauhoi", typeof(string));
    
            var cautraloiParameter = cautraloi != null ?
                new ObjectParameter("cautraloi", cautraloi) :
                new ObjectParameter("cautraloi", typeof(string));
    
            var tentvParameter = tentv != null ?
                new ObjectParameter("tentv", tentv) :
                new ObjectParameter("tentv", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var diaviParameter = diavi != null ?
                new ObjectParameter("diavi", diavi) :
                new ObjectParameter("diavi", typeof(string));
    
            var anhParameter = anh != null ?
                new ObjectParameter("anh", anh) :
                new ObjectParameter("anh", typeof(byte[]));
    
            var dienthoaiParameter = dienthoai != null ?
                new ObjectParameter("dienthoai", dienthoai) :
                new ObjectParameter("dienthoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CapNhatThongTinThanhVien", tendangnhapParameter, matkhauParameter, cauhoiParameter, cautraloiParameter, tentvParameter, ngaysinhParameter, gioitinhParameter, diaviParameter, anhParameter, dienthoaiParameter, emailParameter);
        }
    
        public virtual int SP_ChoVay(Nullable<System.DateTime> ngayvay, Nullable<int> sotien, string matv, string nguoivay)
        {
            var ngayvayParameter = ngayvay.HasValue ?
                new ObjectParameter("ngayvay", ngayvay) :
                new ObjectParameter("ngayvay", typeof(System.DateTime));
    
            var sotienParameter = sotien.HasValue ?
                new ObjectParameter("sotien", sotien) :
                new ObjectParameter("sotien", typeof(int));
    
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var nguoivayParameter = nguoivay != null ?
                new ObjectParameter("nguoivay", nguoivay) :
                new ObjectParameter("nguoivay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ChoVay", ngayvayParameter, sotienParameter, matvParameter, nguoivayParameter);
        }
    
        public virtual int SP_DaThongBaoCongViec(string macv)
        {
            var macvParameter = macv != null ?
                new ObjectParameter("macv", macv) :
                new ObjectParameter("macv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DaThongBaoCongViec", macvParameter);
        }
    
        public virtual int SP_DaXemCanhBao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DaXemCanhBao");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_DemSoCongViecCaNhanChuaHoanThanh(string matv)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_DemSoCongViecCaNhanChuaHoanThanh", matvParameter);
        }
    
        public virtual int SP_DemSoLanTrongThang(Nullable<System.DateTime> batdau, Nullable<System.DateTime> ketthuc)
        {
            var batdauParameter = batdau.HasValue ?
                new ObjectParameter("batdau", batdau) :
                new ObjectParameter("batdau", typeof(System.DateTime));
    
            var ketthucParameter = ketthuc.HasValue ?
                new ObjectParameter("ketthuc", ketthuc) :
                new ObjectParameter("ketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DemSoLanTrongThang", batdauParameter, ketthucParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_DemSoUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_DemSoUser");
        }
    
        public virtual ObjectResult<SP_KhoanChiThangCaNhanTheoLoai_Result> SP_KhoanChiThangCaNhanTheoLoai(string maLKC, string maTV, string dateStart, string dateEnd)
        {
            var maLKCParameter = maLKC != null ?
                new ObjectParameter("MaLKC", maLKC) :
                new ObjectParameter("MaLKC", typeof(string));
    
            var maTVParameter = maTV != null ?
                new ObjectParameter("MaTV", maTV) :
                new ObjectParameter("MaTV", typeof(string));
    
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_KhoanChiThangCaNhanTheoLoai_Result>("SP_KhoanChiThangCaNhanTheoLoai", maLKCParameter, maTVParameter, dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<SP_KhoanChiThangTheoLoai_Result> SP_KhoanChiThangTheoLoai(string maLKC, string dateStart, string dateEnd)
        {
            var maLKCParameter = maLKC != null ?
                new ObjectParameter("MaLKC", maLKC) :
                new ObjectParameter("MaLKC", typeof(string));
    
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_KhoanChiThangTheoLoai_Result>("SP_KhoanChiThangTheoLoai", maLKCParameter, dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<SP_KhoanThuThangCaNhanTheoLoai_Result> SP_KhoanThuThangCaNhanTheoLoai(string maLKT, string maTV, string dateStart, string dateEnd)
        {
            var maLKTParameter = maLKT != null ?
                new ObjectParameter("MaLKT", maLKT) :
                new ObjectParameter("MaLKT", typeof(string));
    
            var maTVParameter = maTV != null ?
                new ObjectParameter("MaTV", maTV) :
                new ObjectParameter("MaTV", typeof(string));
    
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_KhoanThuThangCaNhanTheoLoai_Result>("SP_KhoanThuThangCaNhanTheoLoai", maLKTParameter, maTVParameter, dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<SP_KhoanThuThangTheoLoai_Result> SP_KhoanThuThangTheoLoai(string maLKT, string dateStart, string dateEnd)
        {
            var maLKTParameter = maLKT != null ?
                new ObjectParameter("MaLKT", maLKT) :
                new ObjectParameter("MaLKT", typeof(string));
    
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_KhoanThuThangTheoLoai_Result>("SP_KhoanThuThangTheoLoai", maLKTParameter, dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_KiemTraKhoanTraNo(Nullable<int> khoanvay, Nullable<int> sotien)
        {
            var khoanvayParameter = khoanvay.HasValue ?
                new ObjectParameter("khoanvay", khoanvay) :
                new ObjectParameter("khoanvay", typeof(int));
    
            var sotienParameter = sotien.HasValue ?
                new ObjectParameter("sotien", sotien) :
                new ObjectParameter("sotien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_KiemTraKhoanTraNo", khoanvayParameter, sotienParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_KiemTraMaTV(string matv)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_KiemTraMaTV", matvParameter);
        }
    
        public virtual ObjectResult<SP_LanDangNhapSaiChuXem_Result> SP_LanDangNhapSaiChuXem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LanDangNhapSaiChuXem_Result>("SP_LanDangNhapSaiChuXem");
        }
    
        public virtual ObjectResult<SP_LanDangNhapSaiDaXem_Result> SP_LanDangNhapSaiDaXem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LanDangNhapSaiDaXem_Result>("SP_LanDangNhapSaiDaXem");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Login(string username, string password, string queation, string answer)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var queationParameter = queation != null ?
                new ObjectParameter("Queation", queation) :
                new ObjectParameter("Queation", typeof(string));
    
            var answerParameter = answer != null ?
                new ObjectParameter("Answer", answer) :
                new ObjectParameter("Answer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Login", usernameParameter, passwordParameter, queationParameter, answerParameter);
        }
    
        public virtual ObjectResult<SP_NguoiDung_Result> SP_NguoiDung(string username, string password, string queation, string answer)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var queationParameter = queation != null ?
                new ObjectParameter("Queation", queation) :
                new ObjectParameter("Queation", typeof(string));
    
            var answerParameter = answer != null ?
                new ObjectParameter("Answer", answer) :
                new ObjectParameter("Answer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_NguoiDung_Result>("SP_NguoiDung", usernameParameter, passwordParameter, queationParameter, answerParameter);
        }
    
        public virtual ObjectResult<SP_PhanTrangKhoanChiCaNhan_Result> SP_PhanTrangKhoanChiCaNhan(string matv, string ngaybatdau, string ngayketthuc, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngaybatdauParameter = ngaybatdau != null ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(string));
    
            var ngayketthucParameter = ngayketthuc != null ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("pageIndex", pageIndex) :
                new ObjectParameter("pageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PhanTrangKhoanChiCaNhan_Result>("SP_PhanTrangKhoanChiCaNhan", matvParameter, ngaybatdauParameter, ngayketthucParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<SP_PhanTrangKhoanThuCaNhan_Result> SP_PhanTrangKhoanThuCaNhan(string matv, string ngaybatdau, string ngayketthuc, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngaybatdauParameter = ngaybatdau != null ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(string));
    
            var ngayketthucParameter = ngayketthuc != null ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("pageIndex", pageIndex) :
                new ObjectParameter("pageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PhanTrangKhoanThuCaNhan_Result>("SP_PhanTrangKhoanThuCaNhan", matvParameter, ngaybatdauParameter, ngayketthucParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_SoCongViecTrongNgayChuaHoanThanh(string matv, Nullable<System.DateTime> ngay)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_SoCongViecTrongNgayChuaHoanThanh", matvParameter, ngayParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_SoKhoanChiCaNhan(string matv, string ngaybatdau, string ngayketthuc)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngaybatdauParameter = ngaybatdau != null ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(string));
    
            var ngayketthucParameter = ngayketthuc != null ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_SoKhoanChiCaNhan", matvParameter, ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_SoKhoanThuCaNhan(string matv, string ngaybatdau, string ngayketthuc)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngaybatdauParameter = ngaybatdau != null ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(string));
    
            var ngayketthucParameter = ngayketthuc != null ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_SoKhoanThuCaNhan", matvParameter, ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_SoLanDangNhapSai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_SoLanDangNhapSai");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_SoThongBao(string matv, Nullable<System.DateTime> ngay)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_SoThongBao", matvParameter, ngayParameter);
        }
    
        public virtual int SP_SuaCongViec(string macv, Nullable<System.DateTime> ngay, string gio, string noidung, string thanhvien, Nullable<int> thongbao, Nullable<int> hoanthanh)
        {
            var macvParameter = macv != null ?
                new ObjectParameter("macv", macv) :
                new ObjectParameter("macv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var gioParameter = gio != null ?
                new ObjectParameter("gio", gio) :
                new ObjectParameter("gio", typeof(string));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            var thanhvienParameter = thanhvien != null ?
                new ObjectParameter("thanhvien", thanhvien) :
                new ObjectParameter("thanhvien", typeof(string));
    
            var thongbaoParameter = thongbao.HasValue ?
                new ObjectParameter("thongbao", thongbao) :
                new ObjectParameter("thongbao", typeof(int));
    
            var hoanthanhParameter = hoanthanh.HasValue ?
                new ObjectParameter("hoanthanh", hoanthanh) :
                new ObjectParameter("hoanthanh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuaCongViec", macvParameter, ngayParameter, gioParameter, noidungParameter, thanhvienParameter, thongbaoParameter, hoanthanhParameter);
        }
    
        public virtual int SP_SuaKhoanChi(string makc, string matv, Nullable<System.DateTime> ngay, string loaikc, string khoanchi, Nullable<double> sotien, string ghichu)
        {
            var makcParameter = makc != null ?
                new ObjectParameter("makc", makc) :
                new ObjectParameter("makc", typeof(string));
    
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var loaikcParameter = loaikc != null ?
                new ObjectParameter("loaikc", loaikc) :
                new ObjectParameter("loaikc", typeof(string));
    
            var khoanchiParameter = khoanchi != null ?
                new ObjectParameter("khoanchi", khoanchi) :
                new ObjectParameter("khoanchi", typeof(string));
    
            var sotienParameter = sotien.HasValue ?
                new ObjectParameter("sotien", sotien) :
                new ObjectParameter("sotien", typeof(double));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuaKhoanChi", makcParameter, matvParameter, ngayParameter, loaikcParameter, khoanchiParameter, sotienParameter, ghichuParameter);
        }
    
        public virtual int SP_SuaKhoanThu(string makt, string matv, Nullable<System.DateTime> ngay, string loaikt, string khoanthu, Nullable<double> sotien, string ghichu)
        {
            var maktParameter = makt != null ?
                new ObjectParameter("makt", makt) :
                new ObjectParameter("makt", typeof(string));
    
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var loaiktParameter = loaikt != null ?
                new ObjectParameter("loaikt", loaikt) :
                new ObjectParameter("loaikt", typeof(string));
    
            var khoanthuParameter = khoanthu != null ?
                new ObjectParameter("khoanthu", khoanthu) :
                new ObjectParameter("khoanthu", typeof(string));
    
            var sotienParameter = sotien.HasValue ?
                new ObjectParameter("sotien", sotien) :
                new ObjectParameter("sotien", typeof(double));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuaKhoanThu", maktParameter, matvParameter, ngayParameter, loaiktParameter, khoanthuParameter, sotienParameter, ghichuParameter);
        }
    
        public virtual int SP_SuaLoaiKhoanChi(string malkc, string tenlkc)
        {
            var malkcParameter = malkc != null ?
                new ObjectParameter("malkc", malkc) :
                new ObjectParameter("malkc", typeof(string));
    
            var tenlkcParameter = tenlkc != null ?
                new ObjectParameter("tenlkc", tenlkc) :
                new ObjectParameter("tenlkc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuaLoaiKhoanChi", malkcParameter, tenlkcParameter);
        }
    
        public virtual int SP_SuaLoaiKhoanThu(string malkt, string tenlkt)
        {
            var malktParameter = malkt != null ?
                new ObjectParameter("malkt", malkt) :
                new ObjectParameter("malkt", typeof(string));
    
            var tenlktParameter = tenlkt != null ?
                new ObjectParameter("tenlkt", tenlkt) :
                new ObjectParameter("tenlkt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuaLoaiKhoanThu", malktParameter, tenlktParameter);
        }
    
        public virtual int SP_SuaNguoiVay(string ma, string ten, Nullable<int> sdt)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuaNguoiVay", maParameter, tenParameter, sdtParameter);
        }
    
        public virtual int SP_SuaThanhVien(string tendangnhap, string matkhau, string cauhoi, string cautraloi, string tentv, Nullable<System.DateTime> ngaysinh, string gioitinh, string diavi, byte[] anh, string dienthoai, string email, Nullable<int> quyen)
        {
            var tendangnhapParameter = tendangnhap != null ?
                new ObjectParameter("tendangnhap", tendangnhap) :
                new ObjectParameter("tendangnhap", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var cauhoiParameter = cauhoi != null ?
                new ObjectParameter("cauhoi", cauhoi) :
                new ObjectParameter("cauhoi", typeof(string));
    
            var cautraloiParameter = cautraloi != null ?
                new ObjectParameter("cautraloi", cautraloi) :
                new ObjectParameter("cautraloi", typeof(string));
    
            var tentvParameter = tentv != null ?
                new ObjectParameter("tentv", tentv) :
                new ObjectParameter("tentv", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var diaviParameter = diavi != null ?
                new ObjectParameter("diavi", diavi) :
                new ObjectParameter("diavi", typeof(string));
    
            var anhParameter = anh != null ?
                new ObjectParameter("anh", anh) :
                new ObjectParameter("anh", typeof(byte[]));
    
            var dienthoaiParameter = dienthoai != null ?
                new ObjectParameter("dienthoai", dienthoai) :
                new ObjectParameter("dienthoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var quyenParameter = quyen.HasValue ?
                new ObjectParameter("quyen", quyen) :
                new ObjectParameter("quyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuaThanhVien", tendangnhapParameter, matkhauParameter, cauhoiParameter, cautraloiParameter, tentvParameter, ngaysinhParameter, gioitinhParameter, diaviParameter, anhParameter, dienthoaiParameter, emailParameter, quyenParameter);
        }
    
        public virtual int SP_SuaTheoDoi(Nullable<System.DateTime> ngay, Nullable<int> ketqua)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var ketquaParameter = ketqua.HasValue ?
                new ObjectParameter("ketqua", ketqua) :
                new ObjectParameter("ketqua", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuaTheoDoi", ngayParameter, ketquaParameter);
        }
    
        public virtual int SP_SuaTrangThai(Nullable<int> matt, string matv, Nullable<System.DateTime> ngay, Nullable<System.TimeSpan> gio, Nullable<int> camxuc, string trangthai, byte[] anh)
        {
            var mattParameter = matt.HasValue ?
                new ObjectParameter("matt", matt) :
                new ObjectParameter("matt", typeof(int));
    
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var gioParameter = gio.HasValue ?
                new ObjectParameter("gio", gio) :
                new ObjectParameter("gio", typeof(System.TimeSpan));
    
            var camxucParameter = camxuc.HasValue ?
                new ObjectParameter("camxuc", camxuc) :
                new ObjectParameter("camxuc", typeof(int));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            var anhParameter = anh != null ?
                new ObjectParameter("anh", anh) :
                new ObjectParameter("anh", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuaTrangThai", mattParameter, matvParameter, ngayParameter, gioParameter, camxucParameter, trangthaiParameter, anhParameter);
        }
    
        public virtual int SP_SuaTrangThai1(Nullable<int> matt, string trangthai, Nullable<int> camxuc, byte[] anh)
        {
            var mattParameter = matt.HasValue ?
                new ObjectParameter("matt", matt) :
                new ObjectParameter("matt", typeof(int));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            var camxucParameter = camxuc.HasValue ?
                new ObjectParameter("camxuc", camxuc) :
                new ObjectParameter("camxuc", typeof(int));
    
            var anhParameter = anh != null ?
                new ObjectParameter("anh", anh) :
                new ObjectParameter("anh", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuaTrangThai1", mattParameter, trangthaiParameter, camxucParameter, anhParameter);
        }
    
        public virtual int SP_ThemCongViec(Nullable<System.DateTime> ngay, string gio, string noidung, string thanhvien, Nullable<int> thongbao, Nullable<int> hoanthanh)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var gioParameter = gio != null ?
                new ObjectParameter("gio", gio) :
                new ObjectParameter("gio", typeof(string));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            var thanhvienParameter = thanhvien != null ?
                new ObjectParameter("thanhvien", thanhvien) :
                new ObjectParameter("thanhvien", typeof(string));
    
            var thongbaoParameter = thongbao.HasValue ?
                new ObjectParameter("thongbao", thongbao) :
                new ObjectParameter("thongbao", typeof(int));
    
            var hoanthanhParameter = hoanthanh.HasValue ?
                new ObjectParameter("hoanthanh", hoanthanh) :
                new ObjectParameter("hoanthanh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemCongViec", ngayParameter, gioParameter, noidungParameter, thanhvienParameter, thongbaoParameter, hoanthanhParameter);
        }
    
        public virtual int SP_ThemKhoanChi(string makc, string matv, Nullable<System.DateTime> ngay, string loaikc, string khoanchi, Nullable<double> sotien, string ghichu)
        {
            var makcParameter = makc != null ?
                new ObjectParameter("makc", makc) :
                new ObjectParameter("makc", typeof(string));
    
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var loaikcParameter = loaikc != null ?
                new ObjectParameter("loaikc", loaikc) :
                new ObjectParameter("loaikc", typeof(string));
    
            var khoanchiParameter = khoanchi != null ?
                new ObjectParameter("khoanchi", khoanchi) :
                new ObjectParameter("khoanchi", typeof(string));
    
            var sotienParameter = sotien.HasValue ?
                new ObjectParameter("sotien", sotien) :
                new ObjectParameter("sotien", typeof(double));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemKhoanChi", makcParameter, matvParameter, ngayParameter, loaikcParameter, khoanchiParameter, sotienParameter, ghichuParameter);
        }
    
        public virtual int SP_ThemKhoanThu(string makt, string matv, Nullable<System.DateTime> ngay, string loaikt, string khoanthu, Nullable<double> sotien, string ghichu)
        {
            var maktParameter = makt != null ?
                new ObjectParameter("makt", makt) :
                new ObjectParameter("makt", typeof(string));
    
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var loaiktParameter = loaikt != null ?
                new ObjectParameter("loaikt", loaikt) :
                new ObjectParameter("loaikt", typeof(string));
    
            var khoanthuParameter = khoanthu != null ?
                new ObjectParameter("khoanthu", khoanthu) :
                new ObjectParameter("khoanthu", typeof(string));
    
            var sotienParameter = sotien.HasValue ?
                new ObjectParameter("sotien", sotien) :
                new ObjectParameter("sotien", typeof(double));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemKhoanThu", maktParameter, matvParameter, ngayParameter, loaiktParameter, khoanthuParameter, sotienParameter, ghichuParameter);
        }
    
        public virtual int SP_ThemLanDangNhap(Nullable<System.DateTime> ngay, Nullable<System.TimeSpan> gio, Nullable<int> trangthai, Nullable<int> trangthaixem)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var gioParameter = gio.HasValue ?
                new ObjectParameter("gio", gio) :
                new ObjectParameter("gio", typeof(System.TimeSpan));
    
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(int));
    
            var trangthaixemParameter = trangthaixem.HasValue ?
                new ObjectParameter("trangthaixem", trangthaixem) :
                new ObjectParameter("trangthaixem", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemLanDangNhap", ngayParameter, gioParameter, trangthaiParameter, trangthaixemParameter);
        }
    
        public virtual int SP_ThemLoaiKhoanChi(string malkc, string tenlkc)
        {
            var malkcParameter = malkc != null ?
                new ObjectParameter("malkc", malkc) :
                new ObjectParameter("malkc", typeof(string));
    
            var tenlkcParameter = tenlkc != null ?
                new ObjectParameter("tenlkc", tenlkc) :
                new ObjectParameter("tenlkc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemLoaiKhoanChi", malkcParameter, tenlkcParameter);
        }
    
        public virtual int SP_ThemLoaiKhoanThu(string malkt, string tenlkt)
        {
            var malktParameter = malkt != null ?
                new ObjectParameter("malkt", malkt) :
                new ObjectParameter("malkt", typeof(string));
    
            var tenlktParameter = tenlkt != null ?
                new ObjectParameter("tenlkt", tenlkt) :
                new ObjectParameter("tenlkt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemLoaiKhoanThu", malktParameter, tenlktParameter);
        }
    
        public virtual int SP_ThemNguoiVay(string ma, string ten, Nullable<int> sdt)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemNguoiVay", maParameter, tenParameter, sdtParameter);
        }
    
        public virtual int SP_ThemThanhVien(string tendangnhap, string matkhau, string cauhoi, string cautraloi, string tentv, Nullable<System.DateTime> ngaysinh, string gioitinh, string diavi, byte[] anh, string dienthoai, string email, Nullable<int> quyen)
        {
            var tendangnhapParameter = tendangnhap != null ?
                new ObjectParameter("tendangnhap", tendangnhap) :
                new ObjectParameter("tendangnhap", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var cauhoiParameter = cauhoi != null ?
                new ObjectParameter("cauhoi", cauhoi) :
                new ObjectParameter("cauhoi", typeof(string));
    
            var cautraloiParameter = cautraloi != null ?
                new ObjectParameter("cautraloi", cautraloi) :
                new ObjectParameter("cautraloi", typeof(string));
    
            var tentvParameter = tentv != null ?
                new ObjectParameter("tentv", tentv) :
                new ObjectParameter("tentv", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var diaviParameter = diavi != null ?
                new ObjectParameter("diavi", diavi) :
                new ObjectParameter("diavi", typeof(string));
    
            var anhParameter = anh != null ?
                new ObjectParameter("anh", anh) :
                new ObjectParameter("anh", typeof(byte[]));
    
            var dienthoaiParameter = dienthoai != null ?
                new ObjectParameter("dienthoai", dienthoai) :
                new ObjectParameter("dienthoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var quyenParameter = quyen.HasValue ?
                new ObjectParameter("quyen", quyen) :
                new ObjectParameter("quyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemThanhVien", tendangnhapParameter, matkhauParameter, cauhoiParameter, cautraloiParameter, tentvParameter, ngaysinhParameter, gioitinhParameter, diaviParameter, anhParameter, dienthoaiParameter, emailParameter, quyenParameter);
        }
    
        public virtual int SP_ThemTheoDoi(Nullable<int> ketqua)
        {
            var ketquaParameter = ketqua.HasValue ?
                new ObjectParameter("ketqua", ketqua) :
                new ObjectParameter("ketqua", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemTheoDoi", ketquaParameter);
        }
    
        public virtual int SP_ThemTrangThai(string matv, Nullable<System.DateTime> ngay, Nullable<System.TimeSpan> gio, Nullable<int> camxuc, string trangthai, byte[] anh)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var gioParameter = gio.HasValue ?
                new ObjectParameter("gio", gio) :
                new ObjectParameter("gio", typeof(System.TimeSpan));
    
            var camxucParameter = camxuc.HasValue ?
                new ObjectParameter("camxuc", camxuc) :
                new ObjectParameter("camxuc", typeof(int));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            var anhParameter = anh != null ?
                new ObjectParameter("anh", anh) :
                new ObjectParameter("anh", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemTrangThai", matvParameter, ngayParameter, gioParameter, camxucParameter, trangthaiParameter, anhParameter);
        }
    
        public virtual int SP_TheoDoiTheoThang(Nullable<System.DateTime> batdau, Nullable<System.DateTime> ketthuc)
        {
            var batdauParameter = batdau.HasValue ?
                new ObjectParameter("batdau", batdau) :
                new ObjectParameter("batdau", typeof(System.DateTime));
    
            var ketthucParameter = ketthuc.HasValue ?
                new ObjectParameter("ketthuc", ketthuc) :
                new ObjectParameter("ketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TheoDoiTheoThang", batdauParameter, ketthucParameter);
        }
    
        public virtual ObjectResult<SP_ThongBao_Result> SP_ThongBao(string matv, Nullable<System.DateTime> ngay)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ThongBao_Result>("SP_ThongBao", matvParameter, ngayParameter);
        }
    
        public virtual ObjectResult<SP_ThongBaoCongViec_Result> SP_ThongBaoCongViec(string matv, Nullable<System.DateTime> ngay, string gio)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var gioParameter = gio != null ?
                new ObjectParameter("gio", gio) :
                new ObjectParameter("gio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ThongBaoCongViec_Result>("SP_ThongBaoCongViec", matvParameter, ngayParameter, gioParameter);
        }
    
        public virtual int SP_ThongSoTheoDoi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThongSoTheoDoi");
        }
    
        public virtual ObjectResult<SP_TongChiCaNhanTheoLoai_Result> SP_TongChiCaNhanTheoLoai(string matv, Nullable<System.DateTime> batdau, Nullable<System.DateTime> ketthuc)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var batdauParameter = batdau.HasValue ?
                new ObjectParameter("batdau", batdau) :
                new ObjectParameter("batdau", typeof(System.DateTime));
    
            var ketthucParameter = ketthuc.HasValue ?
                new ObjectParameter("ketthuc", ketthuc) :
                new ObjectParameter("ketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TongChiCaNhanTheoLoai_Result>("SP_TongChiCaNhanTheoLoai", matvParameter, batdauParameter, ketthucParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TongChiCaNhanTrongNgay(string matv, Nullable<System.DateTime> ngay)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TongChiCaNhanTrongNgay", matvParameter, ngayParameter);
        }
    
        public virtual ObjectResult<SP_TongChiTheoLoai_Result> SP_TongChiTheoLoai(Nullable<System.DateTime> batdau, Nullable<System.DateTime> ketthuc)
        {
            var batdauParameter = batdau.HasValue ?
                new ObjectParameter("batdau", batdau) :
                new ObjectParameter("batdau", typeof(System.DateTime));
    
            var ketthucParameter = ketthuc.HasValue ?
                new ObjectParameter("ketthuc", ketthuc) :
                new ObjectParameter("ketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TongChiTheoLoai_Result>("SP_TongChiTheoLoai", batdauParameter, ketthucParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TongChiTheoThang(string dateStart, string dateEnd)
        {
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TongChiTheoThang", dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TongKhoanChiCaNhanTheoLoai(string maLKC, string maTV, string dateStart, string dateEnd)
        {
            var maLKCParameter = maLKC != null ?
                new ObjectParameter("MaLKC", maLKC) :
                new ObjectParameter("MaLKC", typeof(string));
    
            var maTVParameter = maTV != null ?
                new ObjectParameter("MaTV", maTV) :
                new ObjectParameter("MaTV", typeof(string));
    
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TongKhoanChiCaNhanTheoLoai", maLKCParameter, maTVParameter, dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TongKhoanChiThangTheoLoai(string maLKC, string maTV, string dateStart, string dateEnd)
        {
            var maLKCParameter = maLKC != null ?
                new ObjectParameter("MaLKC", maLKC) :
                new ObjectParameter("MaLKC", typeof(string));
    
            var maTVParameter = maTV != null ?
                new ObjectParameter("MaTV", maTV) :
                new ObjectParameter("MaTV", typeof(string));
    
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TongKhoanChiThangTheoLoai", maLKCParameter, maTVParameter, dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TongKhoanChiTheoLoai(string maLKC, string dateStart, string dateEnd)
        {
            var maLKCParameter = maLKC != null ?
                new ObjectParameter("MaLKC", maLKC) :
                new ObjectParameter("MaLKC", typeof(string));
    
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TongKhoanChiTheoLoai", maLKCParameter, dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TongKhoanThuCaNhanTheoLoai(string maLKT, string maTV, string dateStart, string dateEnd)
        {
            var maLKTParameter = maLKT != null ?
                new ObjectParameter("MaLKT", maLKT) :
                new ObjectParameter("MaLKT", typeof(string));
    
            var maTVParameter = maTV != null ?
                new ObjectParameter("MaTV", maTV) :
                new ObjectParameter("MaTV", typeof(string));
    
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TongKhoanThuCaNhanTheoLoai", maLKTParameter, maTVParameter, dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TongKhoanThuTheoLoai(string maLKT, string dateStart, string dateEnd)
        {
            var maLKTParameter = maLKT != null ?
                new ObjectParameter("MaLKT", maLKT) :
                new ObjectParameter("MaLKT", typeof(string));
    
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TongKhoanThuTheoLoai", maLKTParameter, dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<SP_TongThuCaNhanTheoLoai_Result> SP_TongThuCaNhanTheoLoai(string matv, Nullable<System.DateTime> batdau, Nullable<System.DateTime> ketthuc)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var batdauParameter = batdau.HasValue ?
                new ObjectParameter("batdau", batdau) :
                new ObjectParameter("batdau", typeof(System.DateTime));
    
            var ketthucParameter = ketthuc.HasValue ?
                new ObjectParameter("ketthuc", ketthuc) :
                new ObjectParameter("ketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TongThuCaNhanTheoLoai_Result>("SP_TongThuCaNhanTheoLoai", matvParameter, batdauParameter, ketthucParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TongThuCaNhanTrongNgay(string matv, Nullable<System.DateTime> ngay)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TongThuCaNhanTrongNgay", matvParameter, ngayParameter);
        }
    
        public virtual ObjectResult<SP_TongThuChi_Result> SP_TongThuChi(Nullable<System.DateTime> batdau, Nullable<System.DateTime> ketthuc)
        {
            var batdauParameter = batdau.HasValue ?
                new ObjectParameter("batdau", batdau) :
                new ObjectParameter("batdau", typeof(System.DateTime));
    
            var ketthucParameter = ketthuc.HasValue ?
                new ObjectParameter("ketthuc", ketthuc) :
                new ObjectParameter("ketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TongThuChi_Result>("SP_TongThuChi", batdauParameter, ketthucParameter);
        }
    
        public virtual ObjectResult<SP_TongThuTheoLoai_Result> SP_TongThuTheoLoai(Nullable<System.DateTime> batdau, Nullable<System.DateTime> ketthuc)
        {
            var batdauParameter = batdau.HasValue ?
                new ObjectParameter("batdau", batdau) :
                new ObjectParameter("batdau", typeof(System.DateTime));
    
            var ketthucParameter = ketthuc.HasValue ?
                new ObjectParameter("ketthuc", ketthuc) :
                new ObjectParameter("ketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TongThuTheoLoai_Result>("SP_TongThuTheoLoai", batdauParameter, ketthucParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TongThuTheoThang(string dateStart, string dateEnd)
        {
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TongThuTheoThang", dateStartParameter, dateEndParameter);
        }
    
        public virtual int SP_TraNo(Nullable<int> khoanvay, Nullable<System.DateTime> ngaytra, Nullable<int> sotien)
        {
            var khoanvayParameter = khoanvay.HasValue ?
                new ObjectParameter("khoanvay", khoanvay) :
                new ObjectParameter("khoanvay", typeof(int));
    
            var ngaytraParameter = ngaytra.HasValue ?
                new ObjectParameter("ngaytra", ngaytra) :
                new ObjectParameter("ngaytra", typeof(System.DateTime));
    
            var sotienParameter = sotien.HasValue ?
                new ObjectParameter("sotien", sotien) :
                new ObjectParameter("sotien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TraNo", khoanvayParameter, ngaytraParameter, sotienParameter);
        }
    
        public virtual int SP_UpdateCongViec(string macv, Nullable<int> thongbao, Nullable<int> hoanthanh)
        {
            var macvParameter = macv != null ?
                new ObjectParameter("macv", macv) :
                new ObjectParameter("macv", typeof(string));
    
            var thongbaoParameter = thongbao.HasValue ?
                new ObjectParameter("thongbao", thongbao) :
                new ObjectParameter("thongbao", typeof(int));
    
            var hoanthanhParameter = hoanthanh.HasValue ?
                new ObjectParameter("hoanthanh", hoanthanh) :
                new ObjectParameter("hoanthanh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateCongViec", macvParameter, thongbaoParameter, hoanthanhParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_VanTinSoDu(string dateStart, string dateEnd)
        {
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_VanTinSoDu", dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_VanTinSoDuTongHop(Nullable<System.DateTime> batdau, Nullable<System.DateTime> ketthuc)
        {
            var batdauParameter = batdau.HasValue ?
                new ObjectParameter("batdau", batdau) :
                new ObjectParameter("batdau", typeof(System.DateTime));
    
            var ketthucParameter = ketthuc.HasValue ?
                new ObjectParameter("ketthuc", ketthuc) :
                new ObjectParameter("ketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_VanTinSoDuTongHop", batdauParameter, ketthucParameter);
        }
    
        public virtual int SP_VayTien(Nullable<System.DateTime> ngayvay, Nullable<int> sotien, string matv, string nguoivay)
        {
            var ngayvayParameter = ngayvay.HasValue ?
                new ObjectParameter("ngayvay", ngayvay) :
                new ObjectParameter("ngayvay", typeof(System.DateTime));
    
            var sotienParameter = sotien.HasValue ?
                new ObjectParameter("sotien", sotien) :
                new ObjectParameter("sotien", typeof(int));
    
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var nguoivayParameter = nguoivay != null ?
                new ObjectParameter("nguoivay", nguoivay) :
                new ObjectParameter("nguoivay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_VayTien", ngayvayParameter, sotienParameter, matvParameter, nguoivayParameter);
        }
    
        public virtual ObjectResult<SP_XemCongViecCaNhanChuaHoanThanh_Result> SP_XemCongViecCaNhanChuaHoanThanh(string matv)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_XemCongViecCaNhanChuaHoanThanh_Result>("SP_XemCongViecCaNhanChuaHoanThanh", matvParameter);
        }
    
        public virtual ObjectResult<SP_XemCongViecCaNhanSapToi_Result> SP_XemCongViecCaNhanSapToi(string matv, Nullable<System.DateTime> ngaybatdau, Nullable<System.DateTime> ngayketthuc)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngaybatdauParameter = ngaybatdau.HasValue ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(System.DateTime));
    
            var ngayketthucParameter = ngayketthuc.HasValue ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_XemCongViecCaNhanSapToi_Result>("SP_XemCongViecCaNhanSapToi", matvParameter, ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<SP_XemCongViecCaNhanTrongNgay_Result> SP_XemCongViecCaNhanTrongNgay(string matv, Nullable<System.DateTime> ngay)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_XemCongViecCaNhanTrongNgay_Result>("SP_XemCongViecCaNhanTrongNgay", matvParameter, ngayParameter);
        }
    
        public virtual ObjectResult<SP_XemCongViecCaNhanTrongNgayChuaLam_Result> SP_XemCongViecCaNhanTrongNgayChuaLam(string matv, Nullable<System.DateTime> ngay)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_XemCongViecCaNhanTrongNgayChuaLam_Result>("SP_XemCongViecCaNhanTrongNgayChuaLam", matvParameter, ngayParameter);
        }
    
        public virtual ObjectResult<SP_XemKhoanChiCaNhan_Result> SP_XemKhoanChiCaNhan(string matv, Nullable<System.DateTime> ngaybatdau, Nullable<System.DateTime> ngayketthuc)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngaybatdauParameter = ngaybatdau.HasValue ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(System.DateTime));
    
            var ngayketthucParameter = ngayketthuc.HasValue ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_XemKhoanChiCaNhan_Result>("SP_XemKhoanChiCaNhan", matvParameter, ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<SP_XemKhoanThuCaNhan_Result> SP_XemKhoanThuCaNhan(string matv, Nullable<System.DateTime> ngaybatdau, Nullable<System.DateTime> ngayketthuc)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var ngaybatdauParameter = ngaybatdau.HasValue ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(System.DateTime));
    
            var ngayketthucParameter = ngayketthuc.HasValue ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_XemKhoanThuCaNhan_Result>("SP_XemKhoanThuCaNhan", matvParameter, ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<SP_XemLanDangNhapSai_Result> SP_XemLanDangNhapSai(Nullable<System.DateTime> ngay)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_XemLanDangNhapSai_Result>("SP_XemLanDangNhapSai", ngayParameter);
        }
    
        public virtual ObjectResult<SP_XemTatCaCongViecCaNhan_Result> SP_XemTatCaCongViecCaNhan(string matv)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_XemTatCaCongViecCaNhan_Result>("SP_XemTatCaCongViecCaNhan", matvParameter);
        }
    
        public virtual ObjectResult<SP_XemTrangThaiCaNhan_Result> SP_XemTrangThaiCaNhan(string matv)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_XemTrangThaiCaNhan_Result>("SP_XemTrangThaiCaNhan", matvParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> TongKhoanChoVayChuaTra(string matv)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TongKhoanChoVayChuaTra", matvParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> TongKhoanChoVayChuaTraTheoNguoiMinhChoVay(string matv, string nguoivay)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var nguoivayParameter = nguoivay != null ?
                new ObjectParameter("nguoivay", nguoivay) :
                new ObjectParameter("nguoivay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TongKhoanChoVayChuaTraTheoNguoiMinhChoVay", matvParameter, nguoivayParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> TongKhoanVayChuaTra(string matv)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TongKhoanVayChuaTra", matvParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> TongKhoanVayChuaTraTheoNguoiMinhVay(string matv, string nguoivay)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var nguoivayParameter = nguoivay != null ?
                new ObjectParameter("nguoivay", nguoivay) :
                new ObjectParameter("nguoivay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TongKhoanVayChuaTraTheoNguoiMinhVay", matvParameter, nguoivayParameter);
        }
    
        public virtual ObjectResult<XemKhoanChoVayChuaTraTheoNguoiVay_Result> XemKhoanChoVayChuaTraTheoNguoiVay(string matv, string manv)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<XemKhoanChoVayChuaTraTheoNguoiVay_Result>("XemKhoanChoVayChuaTraTheoNguoiVay", matvParameter, manvParameter);
        }
    
        public virtual ObjectResult<XemKhoanVayChuaTraTheoNguoiVay_Result> XemKhoanVayChuaTraTheoNguoiVay(string matv, string manv)
        {
            var matvParameter = matv != null ?
                new ObjectParameter("matv", matv) :
                new ObjectParameter("matv", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<XemKhoanVayChuaTraTheoNguoiVay_Result>("XemKhoanVayChuaTraTheoNguoiVay", matvParameter, manvParameter);
        }
    }
}
