//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MucDichTietKiem
    {
        public MucDichTietKiem()
        {
            this.TietKiems = new HashSet<TietKiem>();
        }
    
        public int id { get; set; }
        public string TenMucDich { get; set; }
        public Nullable<double> SoTienDuKien { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<TietKiem> TietKiems { get; set; }
    }
}
